name: test
  - openeye
  - rdkit
requirements:

    # Base Depends
  - python
  - setuptools
  - openeye-toolkits
  - rdkit
  - pyyaml

    # Testing
  - pytest
  - pytest-cov

    # Dask testing environment
  - dask
  - distributed

    # QCFractal depends, bad form as we are snapshotting github
  - numpy
  - pandas
  - mongodb
  - pymongo
  - tornado
  - requests
  - jsonschema
  - bcrypt
  - cryptography

    # Pip depends
  - pip:
    - git+git://github.com/MolSSI/QCFractal@v0.3.0a#egg=qcfractal
    - git+git://github.com/MolSSI/QCEngine@v0.4.0#egg=qcengine
    - mongoengine
    - pydantic
    - codecov
