language: python

# Run jobs on container-based infrastructure, can be overridden per job
dist: xenial

matrix:
  include:
    # Extra includes for OSX since python language is not available by default on OSX
    - os: osx
      language: generic
      env: PYTHON_VER=3.6

    - os: linux
      python: 3.6
      env: PYTHON_VER=3.6

env:
  global:
    # Location of decrypted OpenEye license file
    - OE_LICENSE="$HOME/oe_license.txt"

before_install:
  # Additional info about the build
  - uname -a
  - df -h
  - ulimit -a

  # Install the Python environemt
  - source devtools/travis-ci/before_install.sh
  - python -V
  - if [ "$TRAVIS_SECURE_ENV_VARS" == true ]; then openssl aes-256-cbc -K $encrypted_d661b4104461_key -iv $encrypted_d661b4104461_iv -in oe_license.txt.enc -out oe_license.txt -d; fi
  - if [ "$TRAVIS_SECURE_ENV_VARS" == false ]; then echo "OpenEye license will not be installed in forks."; fi

install:
    # Create test environment for package
  - python devtools/scripts/conda_env.py -n=test -p=$PYTHON_VER devtools/conda-envs/meta.yaml
  - source activate test

    # Build and install package
  - python setup.py develop --no-deps

before_script:
  - python -V
  - conda list
#  - psql -c "create database test_qcarchivedb;" -U postgres
#  - psql -c "create user qcarchive with password 'mypass';" -U postgres
#  - psql -c "grant all privileges on database test_qcarchivedb to qcarchive;" -U postgres

script:
  - export OE_LICENSE=`pwd`"/oe_license.txt"
  - pytest -vs --cov=fragmenter fragmenter/tests/

notifications:
    email: false

after_success:
  - codecov
