channels:
  - openeye
  - rdkit
  - conda-forge

dependencies:

    # Base Depends
  - python
  - setuptools
  - openeye-toolkits
  - rdkit
  - pyyaml
  - postgresql
  - pip
  - pip:
    - git+git://github.com/openforcefield/cmiles.git@v0.1.5#egg=cmiles